# Default values for stash-percona-xtradb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""
image:
  # Docker registry used to pull Percona XtraDB addon image
  registry: stashed
  # Docker image used to backup/restore Percona XtraDB database
  repository: stash-percona-xtradb
  # Tag of the image that is used to backup/restore Percona XtraDB database.
  # This is usually same as the database version it can backup.
  tag: v2020.08.26-rc.1
backup:
  # Arguments to pass to `mysqldump` command  during bakcup process
  args: "--all-databases"
  # Optional argument sent to backup script
  socatRetry: 30
restore:
  # Arguments to pass to `mysql` command during restore process
  args: ""
  # Optional argument sent to recovery script
  targetAppReplicas: 1
# Number of seconds to wait for the database to be ready before backup/restore process.
waitTimeout: 300
